dreamSix:
  app:
    jwtExpirationMs: 18000000       # 5 hours in milliseconds
    jwtRefreshExpirationMs: 36000000 # 10 hours in milliseconds
    jwtSecret: ZWFnbGVtb3VudCBzb2Z0d2FyZSBwdnQgbHRkIC0gaHlkZXJhYmFk # Make sure this secret is strong and secure


server:
  port: 8080
  servlet:
    context-path: /v1.0/dream6
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testingdb
    username: root
    password: EagleMount_2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # You can adjust the pool size based on your needs

  jpa:
    hibernate:
      ddl-auto: update  # Can be 'none', 'create', 'update', 'validate'
    show-sql: true  # Show SQL queries in the console
    properties:
      hibernate:
        format_sql: true  # Pretty print SQL queries
        dialect: org.hibernate.dialect.MySQLDialect  # Add this line for MySQL

# Optional: Add logging if needed
logging:
  level:
    org.hibernate.SQL: DEBUG  # Log SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log SQL parameter bindings
