dreamSix:
  app:
    jwtExpirationMs: 18000000       # 5 hours in milliseconds
    jwtRefreshExpirationMs: 36000000 # 10 hours in milliseconds
    jwtSecret: ZWFnbGVtb3VudCBzb2Z0d2FyZSBwdnQgbHRkIC0gaHlkZXJhYmFk # Make sure this secret is strong and secure

server:
  servlet:
    context-path: /v1.0/dream6     # Your API versioning base path

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root                    # Your database username
    password: Leela                   # Your database password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10          # Adjust this based on your needs

  jpa:
    hibernate:
      ddl-auto: update               # Options: 'none', 'create', 'update', 'validate'
    show-sql: true                   # Show SQL queries in the console
    properties:
      hibernate:
        format_sql: true             # Pretty print SQL queries
        dialect: org.hibernate.dialect.MySQLDialect   # MySQL specific dialect

logging:
  level:
    org.hibernate.SQL: DEBUG        # Log SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log SQL parameter bindings
